language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover